### Get users
GET http://localhost:3003/api/users

### add new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "johny123",
  "name": "John Malkovich",
  "password": "strongPassword"
}